import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import ConvexClientProvider from "./ConvexClientProvider";
import { NotificationDisplay } from "@/components/custom/NotificationComponents";
import SettingsModal from "@/components/custom/SettingsModal";
import ClientInitializer from "./ClientInitializer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body>
        <ConvexClientProvider>
        <Provider>
          <ClientInitializer>
            {children}
            <NotificationDisplay />
            <SettingsModal />
          </ClientInitializer>
        </Provider>
        </ConvexClientProvider>
        
      </body>
    </html>
  );
}
